### ISSUE TITLE
ページ描画を早くする

### ISSUE THREAD

**Issue by naofumi0628** [dlnp2/rooms_app#1]
いま、マップを読み込む際に十数秒の時間がかってしまっています。
アプリ改良を進める上で、ページの読み込み速度に時間がかかると、その分待ち時間が増えてしまうので、まずはここを早くしましょう！

アウトプットそのままで早くする工夫が出来れば一番ですが、難しい時は
- データ数を絞る
- マップの描画範囲を絞る
等で、1秒未満まで落とし込むと今後の開発が効率的に進められると思います。

**Comment by dlnp2** [comment]
ご提案ありがとうございます！  
読み込みに十数秒かかっていた主要因は、一定時間アクセスがなかった場合Herokuがスリープ状態になってしまうために起動時間を要することでした。  
これはスケジューラの利用で解決しましたが、未だ４秒ほどかかるため軽量化してみます。

**Comment by dlnp2** [comment]
@naofumi0628 さん  
- HerokuからAWSに以降（Rails/PostgreSQL環境を整備しました）
- データフォーマットをGeoJSONからTopoJSONに変更し、オブジェクトをPolygonからMultiPolygonに変更して描画回数を削減
- もともと透過度０で表示していたデータの取得を停止  
という対応をして表示の高速化をしました。下記URLにてご確認ください。  
[http://ec2-52-69-101-144.ap-northeast-1.compute.amazonaws.com:3000/](http://ec2-52-69-101-144.ap-northeast-1.compute.amazonaws.com:3000/)

**Comment by naofumi0628** [comment]
非常に良いですね！ありがとうございます！

次回から、コードにアップデートがあった際は、マージ前にプルリクエストを頂けると更に良いかもです。
このメッセージご確認頂いたら Issue も Close しちゃってください！
